path: 'https://test-stand.gb.ru/gateway/login'
username: 'Monica Kunde V'
password: 'add9b80be1'
title: 'Кунгурская ледяная пешера'
description: 'Жемчужина Урала'
content: 'Одна из крупнейших карстовых пещер в Европейской части России, седьмая в мире гипсовая пещера по протяжённости.
          Протяжённость пещеры по данным на 2021 год составляет около 8153 м, из них около 2 километров оборудовано для
          посещений туристами. Температура воздуха в центре пещеры от +5 °C до −2 °C, относительная влажность в центре
          пещеры — 100 %. Кунгурская пещера содержит 58 гротов, 70 озёр, 146 т. н. «органных труб» (самая высокая — в 
          Эфирном гроте, 22 м) — высоких шахт, доходящих почти до поверхности. Возраст пещеры оценивается в 10-12 
          тысяч лет. Пещера находится в Пермском крае, на правом берегу реки Сылвы на окраине города Кунгур в селе 
          Филипповка, в 100 км от Перми.'